- name: Set up Android SDK and Accept Licenses
  run: |
    # Create SDK directories
    sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
    cd /usr/lib/android-sdk/cmdline-tools
    sudo mkdir latest
    cd latest

    # Download and extract command line tools
    sudo wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    sudo unzip -o commandlinetools-linux-11076708_latest.zip
    sudo rm -f commandlinetools-linux-11076708_latest.zip

    # Set environment variables (fix path issue)
    export ANDROID_HOME=/usr/lib/android-sdk
    export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

    # Accept licenses and install SDK components
    yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
    yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update || true
    $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
