name: Android Build (Buildozer)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python (Buildozer requires Python 3.10+)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Cache .buildozer to speed up next builds
      - name: Cache buildozer .buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel git
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      # 5️⃣ Initialize buildozer if not done
      - name: Initialize buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # 6️⃣ Build APK
      - name: Build release APK
        run: |
          buildozer -v android debug

      # 7️⃣ Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
