name: Android Build (Buildozer)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zip \
            unzip \
            git \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            liblzma-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libfreetype6-dev \
            python3-pip

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build release APK
        run: |
          buildozer -v android debug
        env:
          ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
          ANDROIDAPI: 34
          ANDROIDMINAPI: 21

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
      - name: Cache buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
