name: Android Build (Buildozer)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # ✅ Avoids autoconf 2.72 issues
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip \
            autoconf automake libtool pkg-config

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer==1.5.0 Cython==0.29.37
          pip install --upgrade python-for-android

      - name: Cache Buildozer global data
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Patch libffi macros (bonus safeguard)
        run: |
          find ~/.buildozer/android/platform/python-for-android -type f -name "configure.ac" \
            -exec sed -i 's/AC_TRY_COMPILE/AC_COMPILE_IFELSE/g' {} \; || true
          find ~/.buildozer/android/platform/python-for-android -type f -name "configure.ac" \
            -exec sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' {} \; || true
          find ~/.buildozer/android/platform/python-for-android -type f -name "AC_TRY_RUN" \
            -exec sed -i 's/AC_TRY_RUN/AC_RUN_IFELSE/g' {} \; || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
