name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (required by latest Android Gradle plugin)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Set up Gradle cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      # Step 4: Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 5: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 6 (Optional): Build Release APK
      # Uncomment if you have signing configs set in gradle.properties
      # - name: Build Release APK
      #   run: ./gradlew assembleRelease

      # Step 7: Upload Debug APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
