name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk zip unzip git
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Prepare buildozer
        run: |
          buildozer init || true
          buildozer android debug || true

      - name: Retry build (actual compile)
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: inhand-apk
          path: bin/*.apk
